version: '3.8'
services:
  postgres_db:
    container_name: 'postgresdb'
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=images
    ports:
      - '5432:5432'